export const ITEMS_VIDEOS = [
    { title: "Gabriela Rocha - ME ATRAIU (AO VIVO)", channelName: "Gabriela Rocha", views: "159 mi de visualizações", bannerImg: "https://i.ytimg.com/vi/Z6cONvRUFZQ/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDSE3tBDRRs4kt9n0YQtW9rSDHY7Q", channelImg: "https://yt3.ggpht.com/9_KONKgpoSQsxHhMu2UAJLS_s63uiHY37VGc3YgeLhdCxfaF4P2tqQk0TuyVsd9Y_cVNY-DrVw=s88-c-k-c0x00ffffff-no-nd-rj"},
    { title: "Top Christmas 🎄 Songs Playlist Classic Christmas Music with Fareplace Merry Christmas", channelName: "Timeless Music", views: "572 visualizações", bannerImg: "https://i.ytimg.com/vi/lE24-b3zHvg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB1AaAAuADigIMCAAQARh_IFAoIjAP&rs=AOn4CLAszTsyQ_5nhwJ0UCcheSdQgMZapw", channelImg: "https://yt3.ggpht.com/6Ylkn7CU7uCpkXgkGmN67RC1dfVe5s6VEEQZmEq8lYYT0SzIy9DQWhXS_5Iz7zh6T_J7qyRR=s68-c-k-c0x00ffffff-no-rj"},
    { title: "Akon - Don't Matter (Official Music Video)", channelName: "Akon", views: "585 mi de visualizações", bannerImg: "https://i.ytimg.com/vi/JWA5hJl4Dv0/hqdefault.jpg?sqp=-oaymwEXCOADEI4CSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBXJkzy4kIAaWncy_zdTIk8ccAjHA", channelImg: "https://yt3.ggpht.com/6Q7HnHvl9CBabGWJCGZmLaBuPHry-2FmzQ04vDHArShVsUg7pYSgpDge4O42j9WdQ5X0nD1L=s88-c-k-c0x00ffffff-no-nd-rj"},
    { title: "Christmas Lofi 🎄 Music calm your mind at Christmas ⛄ 24/7 Lofi hip hop radio", channelName: "Lotus Vibes", views: "1 mil visualizações", bannerImg: "https://i.ytimg.com/vi/JM-2nzSf7Q0/hq720_live.jpg?sqp=CMS5x6sG-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBEidaZJ-USgsyPlcR0khiJqMxDTw", channelImg: "https://yt3.ggpht.com/qiGNGJu-25yldTp_F3mlRm7T2kzCHX-WZHSzx7D9Jnn_u-UOoE2eEBDB-ilWxehvBqoSMbkv2w=s68-c-k-c0x00ffffff-no-rj"},
    { title: "Pitty - Na Sua Estante (Clipe Oficial)", channelName: "Pitty", views: "185 mi de visualizações", bannerImg: "https://i.ytimg.com/vi/DP3j6hgS4VY/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAh4VpFp1qfBGX1coYb4MVxxAsV0w", channelImg: "https://yt3.ggpht.com/oBDcVcJ5GoPAL2bf_FsIsWF-Cak9V9cvdR5mECUTWdV9ktP4tSRsFiwPOY5WjlAE3sY-a-sd8A=s88-c-k-c0x00ffffff-no-rj"},
    { title: "3-Hour Study with Me / Shanghai Night / Pomodoro 50-10/ mix songs pop", channelName: "Sean Study", views: "302 mil visualizações", bannerImg: "https://i.ytimg.com/vi/Ve_1XZkG65U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA1S4e_lymXQduR0jMsRIfBQb2MkA", channelImg: "https://yt3.ggpht.com/TwG5nf7NiaNZkFuN3Jni4UaGuzuvAdDNqaPutqDrYF4yiwM3WJH46omUIkh3yKc8CgLyOBak4Q=s88-c-k-c0x00ffffff-no-rj"},
    { title: "VINHO E PÃO | IPALPHA Música", channelName: "IPALPHA", views: "243 mil visualizações", bannerImg: "https://i.ytimg.com/vi/JheqX_w3m08/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAnneURXQAxp6qTGDQTqDOd1uHvWw", channelImg: "https://yt3.ggpht.com/4C0g3CYCZXjDfxKiHxmpjs11ChB9aDkv1FJ13XC78uP2JNOGP7zAaEcN7G_cXUrRWoLvymH_tA=s68-c-k-c0x00ffffff-no-rj"},
    { title: "2hr study with me | rain sound with gentle piano | pomodoro 50 - 10", channelName: "That Study Phurong", views: "419 mil visualizações", bannerImg: "https://i.ytimg.com/vi/R-_CMhHLb-U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAi412ZdKy71sI5fgByZf2ASsXQTg", channelImg: "https://yt3.ggpht.com/RWCtJpREoyyvpodlSvUufhUJeI6NhTgPpnA-xsJT_fUwFhbj67W-LqbBYZUPsjzIKdFaXznKSg=s68-c-k-c0x00ffffff-no-rj"}
]